import { Question } from './types';

export const githubFindsQuestionsPart3: Question[] = [
    // --- Unique Choice Questions ---
    {
        id: 'gh-finds-3-1',
        phase: 'Github finds',
        text: 'In computing virtualization, which component is responsible for allocating CPU and memory to virtual machines?',
        options: [
            'A. Guest OS',
            'B. VMM / Hypervisor',
            'C. Host OS',
            'D. Hardware'
        ],
        correctAnswers: ['B'],
        type: 'unique'
    },
    {
        id: 'gh-finds-3-2',
        phase: 'Github finds',
        text: 'Which of the following belongs to North-South traffic?',
        options: [
            'A. Traffic between virtual machines within the same data center',
            'B. Traffic generated by customers accessing data center services via the Internet',
            'C. Traffic generated by virtual machine hot migration',
            'D. Traffic between virtual machines across different data centers'
        ],
        correctAnswers: ['B'],
        type: 'unique'
    },
    {
        id: 'gh-finds-3-3',
        phase: 'Github finds',
        text: 'For scenarios such as archives that need to store large amounts of data for a long time but do not need frequent reading, which type of disk is recommended?',
        options: [
            'A. SSD',
            'B. SAS',
            'C. SATA',
            'D. NL-SAS'
        ],
        correctAnswers: ['C'],
        type: 'unique'
    },
    {
        id: 'gh-finds-3-4',
        phase: 'Github finds',
        text: 'Which of the following is NOT part of snapshot management?',
        options: [
            'A. Creating a snapshot',
            'B. Modifying a snapshot',
            'C. Restoring a snapshot',
            'D. Copying a snapshot'
        ],
        correctAnswers: ['D'],
        type: 'unique'
    },
    {
        id: 'gh-finds-3-5',
        phase: 'Github finds',
        text: 'Which of the following is NOT an element of artificial intelligence?',
        options: [
            'A. Big data',
            'B. Emotional analysis capability',
            'C. Computing power',
            'D. Scenario/Application'
        ],
        correctAnswers: ['B'],
        type: 'unique'
    },
    {
        id: 'gh-finds-3-6',
        phase: 'Github finds',
        text: 'User chooses the number of CPU cores when using cloud computing but cannot know the specific model. Which characteristic of cloud computing does this reflect?',
        options: [
            'A. Broad network access',
            'B. Resource pooling',
            'C. Rapid elasticity',
            'D. Measured service'
        ],
        correctAnswers: ['B'],
        type: 'unique'
    },
    {
        id: 'gh-finds-3-7',
        phase: 'Github finds',
        text: 'XEN supports full virtualization and paravirtualization. Its virtual machines are divided into which two categories?',
        options: [
            'A. Dom0 and DomU',
            'B. Host and Guest',
            'C. Kernel and User',
            'D. Active and Standby'
        ],
        correctAnswers: ['A'],
        type: 'unique'
    },
    {
        id: 'gh-finds-3-8',
        phase: 'Github finds',
        text: 'In virtualization, traffic is divided into North-South and East-West. Which of the following is incorrect about North-South traffic?',
        options: [
            'A. It refers to traffic between the data center and the external network',
            'B. It typically passes through gateways and firewalls',
            'C. Traffic that does not pass through a router is North-South traffic',
            'D. It is horizontal traffic between internal servers'
        ],
        correctAnswers: ['C', 'D'],
        type: 'multi'
    },
    {
        id: 'gh-finds-3-9',
        phase: 'Github finds',
        text: 'RAID 5 requires a minimum of how many hard disks?',
        options: [
            'A. 2',
            'B. 3',
            'C. 4',
            'D. 5'
        ],
        correctAnswers: ['B'],
        type: 'unique'
    },
    {
        id: 'gh-finds-3-10',
        phase: 'Github finds',
        text: 'To support virtualization, what technology did Intel add to its CPUs?',
        options: [
            'A. AMD-V',
            'B. VT-x / VT-d',
            'C. SR-IOV',
            'D. VMDQ'
        ],
        correctAnswers: ['B'],
        type: 'unique'
    },

    // --- Boolean Questions ---
    {
        id: 'gh-finds-3-11',
        phase: 'Github finds',
        text: 'A virtual machine can have multiple virtual network cards at the same time, corresponding to different virtual switches.',
        options: ['True', 'False'],
        correctAnswers: ['True'],
        type: 'boolean'
    },
    {
        id: 'gh-finds-3-12',
        phase: 'Github finds',
        text: 'SATA disks use a parallel interface, while SAS disks use a serial interface.',
        options: ['True', 'False'],
        correctAnswers: ['False'],
        type: 'boolean'
    },
    {
        id: 'gh-finds-3-13',
        phase: 'Github finds',
        text: 'The IoT function can only collect data generated by various physical objects.',
        options: ['True', 'False'],
        correctAnswers: ['False'],
        type: 'boolean'
    },
    {
        id: 'gh-finds-3-14',
        phase: 'Github finds',
        text: 'CPU hardware virtualization adds a root mode to the CPU, allowing privileged and sensitive instructions to be executed automatically on the hypervisor.',
        options: ['True', 'False'],
        correctAnswers: ['True'],
        type: 'boolean'
    },
    {
        id: 'gh-finds-3-15',
        phase: 'Github finds',
        text: 'The Virtual Machine Guest OS controls the mapping from virtual addresses to guest physical addresses and can directly access the machine memory.',
        options: ['True', 'False'],
        correctAnswers: ['False'],
        type: 'boolean'
    },
    {
        id: 'gh-finds-3-16',
        phase: 'Github finds',
        text: 'The distributed virtual switch used in Huawei virtualization products is one of the conditions for hot migration of virtual machines.',
        options: ['True', 'False'],
        correctAnswers: ['True'],
        type: 'boolean'
    },
    {
        id: 'gh-finds-3-17',
        phase: 'Github finds',
        text: 'After using NUMA, the CPU will form a NUMA Node with the bound memory. Each node has its own CPU, bus, and memory to improve efficiency.',
        options: ['True', 'False'],
        correctAnswers: ['True'],
        type: 'boolean'
    },
    {
        id: 'gh-finds-3-18',
        phase: 'Github finds',
        text: 'Storage virtualization primarily solves the communication problem of virtual machines after calculation virtualization.',
        options: ['True', 'False'],
        correctAnswers: ['False'],
        type: 'boolean'
    },
    {
        id: 'gh-finds-3-19',
        phase: 'Github finds',
        text: 'In Huawei FusionCompute, for a Windows VM, if the IP address is found to be 0.0.0.0, it is possible that Tools is not installed.',
        options: ['True', 'False'],
        correctAnswers: ['True'],
        type: 'boolean'
    },
    {
        id: 'gh-finds-3-20',
        phase: 'Github finds',
        text: 'Intelligent memory overcommitment technology (ballooning, swapping, sharing) can be custom enabled/disabled for any single function according to customer needs.',
        options: ['True', 'False'],
        correctAnswers: ['False'],
        type: 'boolean'
    },

    // --- Multi Choice Questions ---
    {
        id: 'gh-finds-3-21',
        phase: 'Github finds',
        text: 'Which of the following are advantages of SSD (Solid State Drive)?',
        options: [
            'A. Fast reading speed',
            'B. Good vibration resistance',
            'C. Long lifespan',
            'D. Lower cost'
        ],
        correctAnswers: ['A', 'B'],
        type: 'multi'
    },
    {
        id: 'gh-finds-3-22',
        phase: 'Github finds',
        text: 'Which of the following are mature technologies for SAN currently?',
        options: [
            'A. FC SAN',
            'B. IP SAN',
            'C. FCoE SAN',
            'D. DAS'
        ],
        correctAnswers: ['A', 'B', 'C'],
        type: 'multi'
    },
    {
        id: 'gh-finds-3-23',
        phase: 'Github finds',
        text: 'Which of the following are characteristics of NFS?',
        options: [
            'A. Independent of transport protocol',
            'B. No additional software required',
            'C. Error recovery available',
            'D. Retains file format characteristics'
        ],
        correctAnswers: ['A', 'C', 'D'],
        type: 'multi'
    },
    {
        id: 'gh-finds-3-24',
        phase: 'Github finds',
        text: 'Which of the following are memory QoS parameters?',
        options: [
            'A. Memory resource shares',
            'B. Memory resource policy',
            'C. Memory resource reservation',
            'D. Memory resource limit'
        ],
        correctAnswers: ['A', 'C', 'D'],
        type: 'multi'
    },
    {
        id: 'gh-finds-3-25',
        phase: 'Github finds',
        text: 'Which of the following descriptions about VM encapsulation are correct?',
        options: [
            'A. VM configuration files contain info like CPU type and quantity',
            'B. VM can be migrated from one physical host to another',
            'C. Multiple VMs can run simultaneously on one physical host',
            'D. If a VM has multiple hard disks, each will generate a corresponding disk file'
        ],
        correctAnswers: ['A', 'B', 'D'],
        type: 'multi'
    },
    {
        id: 'gh-finds-3-26',
        phase: 'Github finds',
        text: 'In Huawei FusionCompute, which factors take effect for DRS (Dynamic Resource Scheduler) VM migration?',
        options: [
            'A. Memory',
            'B. I/O',
            'C. Network traffic',
            'D. CPU'
        ],
        correctAnswers: ['A', 'D'],
        type: 'multi'
    },
    {
        id: 'gh-finds-3-27',
        phase: 'Github finds',
        text: 'Which of the following are common external storage solutions?',
        options: [
            'A. DAS',
            'B. NAS',
            'C. NFS',
            'D. SAN'
        ],
        correctAnswers: ['A', 'B', 'D'],
        type: 'multi'
    },
    {
        id: 'gh-finds-3-28',
        phase: 'Github finds',
        text: 'Which of the following are the 4V characteristics of Big Data?',
        options: [
            'A. Value',
            'B. Variety',
            'C. Velocity',
            'D. Volume'
        ],
        correctAnswers: ['A', 'B', 'C', 'D'],
        type: 'multi'
    },
    {
        id: 'gh-finds-3-29',
        phase: 'Github finds',
        text: 'Which of the following are current application areas of AI?',
        options: [
            'A. Service robots',
            'B. Speech recognition',
            'C. Image recognition',
            'D. NLP (Natural Language Processing)'
        ],
        correctAnswers: ['A', 'B', 'C', 'D'],
        type: 'multi'
    },
    {
        id: 'gh-finds-3-30',
        phase: 'Github finds',
        text: 'Which of the following components are involved in VM external communication?',
        options: [
            'A. Port group',
            'B. DVS (Distributed Virtual Switch)',
            'C. Virtual network card (vNIC)',
            'D. Physical network card (pNIC)'
        ],
        correctAnswers: ['A', 'B', 'C', 'D'],
        type: 'multi'
    }
];
